# Generated by Django 4.2.23 on 2025-06-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deslizamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norte', models.FloatField()),
                ('sur', models.FloatField()),
                ('este', models.FloatField()),
                ('oeste', models.FloatField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
