# Generated by Django 4.2.23 on 2025-06-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeslizamientosMonitoreados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('norte', models.FloatField()),
                ('sur', models.FloatField()),
                ('este', models.FloatField()),
                ('oeste', models.FloatField()),
                ('nivel_movimiento', models.FloatField()),
            ],
        ),
    ]
