# Generated by Django 4.2.23 on 2025-07-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion', '0003_deslizamientosmonitoreados_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FincasCafeterasMonitoreadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_municipio', models.CharField(max_length=10)),
                ('municipio', models.CharField(max_length=100)),
                ('lista', models.CharField(max_length=100)),
                ('nombre_vereda', models.CharField(max_length=100)),
                ('nombre_finca', models.CharField(max_length=100)),
                ('longitud', models.FloatField()),
                ('latitud', models.FloatField()),
                ('estado_finca', models.CharField(max_length=50)),
                ('area_total', models.FloatField()),
                ('area_cafe', models.FloatField()),
                ('luminosidad', models.CharField(max_length=50)),
            ],
        ),
    ]
