# Generated by Django 4.2.23 on 2025-07-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion', '0004_fincascafeterasmonitoreadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='deslizamientosmonitoreados',
            name='icono',
            field=models.CharField(default='signal', max_length=100),
        ),
        migrations.AlterField(
            model_name='fincascafeterasmonitoreadas',
            name='area_cafe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fincascafeterasmonitoreadas',
            name='area_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fincascafeterasmonitoreadas',
            name='codigo_municipio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fincascafeterasmonitoreadas',
            name='estado_finca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fincascafeterasmonitoreadas',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fincascafeterasmonitoreadas',
            name='lista',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fincascafeterasmonitoreadas',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fincascafeterasmonitoreadas',
            name='luminosidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fincascafeterasmonitoreadas',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fincascafeterasmonitoreadas',
            name='nombre_finca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fincascafeterasmonitoreadas',
            name='nombre_vereda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
