# Generated by Django 4.2.23 on 2025-07-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion', '0005_deslizamientosmonitoreados_icono_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deslizamiento',
            old_name='creado',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='deslizamiento',
            old_name='este',
            new_name='latitud',
        ),
        migrations.RenameField(
            model_name='deslizamiento',
            old_name='norte',
            new_name='longitud',
        ),
        migrations.RemoveField(
            model_name='deslizamiento',
            name='oeste',
        ),
        migrations.RemoveField(
            model_name='deslizamiento',
            name='sur',
        ),
        migrations.AddField(
            model_name='deslizamiento',
            name='deslizamiento_antiguo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deslizamiento',
            name='deslizamiento_nuevo',
            field=models.BooleanField(default=False),
        ),
    ]
