# Generated by Django 4.2.23 on 2025-07-05 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion', '0007_rename_deslizamiento_antiguo_deslizamiento_deslizamiento_prediccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deslizamiento',
            name='fecha_deslizamiento_prediccion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='deslizamiento',
            name='fecha_deslizamiento_real',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
