# Generated by Django 4.2.23 on 2025-07-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion', '0008_alter_deslizamiento_fecha_deslizamiento_prediccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deslizamiento',
            name='deslizamiento_prediccion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='deslizamiento',
            name='deslizamiento_real',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='deslizamiento',
            name='fecha_deslizamiento_real',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='deslizamiento',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deslizamiento',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
