# Generated by Django 4.2.23 on 2025-07-05 09:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion', '0009_alter_deslizamiento_deslizamiento_prediccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deslizamiento',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='deslizamiento',
            name='longitud',
        ),
        migrations.AddField(
            model_name='deslizamiento',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
