# Generated by Django 4.2.23 on 2025-07-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion', '0010_remove_deslizamiento_latitud_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deslizamiento',
            old_name='location',
            new_name='ubicacion',
        ),
    ]
