# Generated by Django 4.2.23 on 2025-07-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion', '0011_rename_location_deslizamiento_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deslizamiento',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='deslizamiento',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deslizamiento',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
