# Generated by Django 4.2.23 on 2025-07-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion', '0012_remove_deslizamiento_ubicacion_deslizamiento_latitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deslizamientosmonitoreados',
            name='este',
        ),
        migrations.RemoveField(
            model_name='deslizamientosmonitoreados',
            name='norte',
        ),
        migrations.RemoveField(
            model_name='deslizamientosmonitoreados',
            name='oeste',
        ),
        migrations.RemoveField(
            model_name='deslizamientosmonitoreados',
            name='sur',
        ),
        migrations.AddField(
            model_name='deslizamientosmonitoreados',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deslizamientosmonitoreados',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deslizamientosmonitoreados',
            name='nivel_movimiento',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
