# Generated by Django 4.2.23 on 2025-07-09 04:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion', '0013_remove_deslizamientosmonitoreados_este_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeslizamientosReportados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('nombre_reportero', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Reportero (Opcional)')),
                ('contacto_reportero', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto (Email/Teléfono - Opcional)')),
                ('fecha_evento_aproximada', models.DateField(blank=True, null=True, verbose_name='Fecha Aproximada del Evento')),
                ('hora_evento_aproximada', models.TimeField(blank=True, null=True, verbose_name='Hora Aproximada del Evento')),
            ],
        ),
    ]
